language: node_js
cache:
  directories:
  - src/node_modules
  - src/server/node_modules
  - src/client/node_modules
node_js:
  - "7"
before_script:
  - cd src
  - npm install
  - npm install --prefix server
  - npm install --prefix client
  - mv server/config/config-ci.js server/config/config.js
script: npm run ci
