language: node_js
cache:
  directories:
  - src/node_modules
  - src/server/node_modules
  - src/client/node_modules
services:
  - postgresql
node_js:
  - "7"
before_script:
  - npm install
  - npm install --prefix server
  - npm install --prefix client
  - mv server/config/config-ci.js server/config/config.js
  - psql -c 'create database "easypick-development";' -U postgres
script: npm run ci
